### ISSUE TITLE
Managing projects and scope

### ISSUE THREAD

**Issue by hahmed** [Haacked/feedback#171]
👋 Just have a few questions on how you manage your projects at GitHub and elsewhere.

- How do you manage scope and projects for your teams?
- Do project usually meet their deadlines?
- Do you *have* deadlines?
- How do you manage scope creep and technical debt?

Thanks

**Comment by haacked** [comment]
* How do you manage scope and projects for your teams?

I'm in charge of four teams at GitHub. Each team has their own general approach to managing scope and projects. I personally am pretty hands off of specifying scope and projects. The Atom team has a monthly release plan. Electron works with the community to specify releases. The Desktop and GHfVS teams tends to plan releases around a set of features.

* Do project usually meet their deadlines?

Yes, when we have them. We're often able to manage scope in order to hit deadlines when we have them.

* Do you have deadlines?

In general, we don't. Often deadlines are fantasies made up by folks who want to exert a sense of control over a naturally dynamic process. However, sometimes, we have real deadlines such as when we want to release a particular feature for a conference. Or when we're partnering with another team.

Some of my teams have a regular release cadence which you could call a deadline. But they get the choice of managing what scope hits each release.

* How do you manage scope creep and technical debt?

For scope creep, we try and focus on the essential problem we're solving and try and do as little as possible to address it. It takes a bit of discipline.

For technical debt, the best thing to do is not incur it in the first place. The second best thing is to schedule time to pay it down as part of every release. Sometimes, teams will even have a bug bash month. I like to make it part of our continuous improvement approach and pay it down all the time.
