### ISSUE TITLE
Open Source the code for Github desktop wpf app

### ISSUE THREAD

**Issue by manojtrek** [Haacked/feedback#183]
Hi Phil, 

Thanks so much for all your work on blogs/code 👍 

Since github has ditched the WPF based Github Desktop app for electron (We love electron...), I am wondering why it is not open sourced yet, It would be great help for the community who would like to know how github used libgitsharp c# library.

Let me know your thoughts on that...

**Comment by haacked** [comment]
At the time we wrote the app, we didn’t have OSS in mind unlike the new Desktop app.

Going from closed source to open is sometimes harder than it looks. We have dependencies on internal systems. The history needs to be scrubbed. Etc. etc.

Also, we’re very busy building the future of Desktop. Throwing the source code over the wall would be a distraction because the code isn’t as well factored as we’d like. It’d create more questions than answers. And a lot of the techniques we used have been supplanted by better approaches.

I’m not sure what exactly you’d want to learn from it, but you might consider looking at the code in:

* https://github.com/Microsoft/Git-Credential-Manager-for-Windows/tree/master/GitHub.Authentication
* https://github.com/github/visualstudio

A lot of the interesting UI code there was extracted from GitHub for Windows and improved upon. And those projects are OSS and maintained.

Hope that helps.

**Comment by knocte** [comment]
> https://github.com/github/visual-studio

That's a 404.

**Comment by knocte** [comment]
> That's a 404.

Found the correct link: https://github.com/github/VisualStudio

**Comment by haacked** [comment]
@knocte whoops! Thanks! I corrected my original comment.
